# Generated by Django 5.0.6 on 2024-06-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSystem', '0002_chathistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatHistory',
            new_name='AivleChatHistory',
        ),
    ]
